src/js/firstDiscoveryEditor.js, src/js/navButtons.js, src/lib/infusion/VERSION.md, src/lib/infusion/infusion-custom.js, src/lib/infusion/src/framework/preferences/css/Enactors.css, src/lib/infusion/src/framework/preferences/css/stylus/Enactors.styl, src/schemas/schemas.js, tests/js/firstDiscoveryEditorTests.js
http://issues.fluidproject.org/browse/FLOE-254
Updated the infusion lib to use the master branch that has the speak enactor merged in. Also updated the existing components in the first discovery tool to work with non-relay components.
This pull request is dependent on another pull request https://github.com/fluid-project/first-discovery/pull/5 that needs to be merged first.
=> FLOE-254: Updates the infusoin library.

src/css/style.css, src/html/contrast.html, src/html/rangeTemplate.html, src/html/tts.html
@jhung, could you have a look at this?
=> FLOE-261: Styling fixes

src/lib/infusion/VERSION.md, src/lib/infusion/infusion-custom.js
Upgraded to the latest version of infusion to get the bug fixes from FLUID-5593
=> FLOE-260: Infusion upgrade

src/css/style.css
@jhung, do you have a minute to review this one?
=> FLOE-260: Change the mute icon when button pressed

src/js/ttsHookup.js, tests/all-tests.html, tests/html/firstDiscoveryEditor-Tests.html, tests/html/ttsHookup-Tests.html, tests/js/firstDiscoveryEditorTests.js, tests/js/ttsHookupTests.js
http://issues.fluidproject.org/browse/FLOE-269
=> FLOE-269: press 'h' to read panel instructions

demos/index.html, src/css/style.css, src/html/contrast.html, src/html/rangeTemplate.html
@acheetham - can you take a look at this? 
Reference: FLOE-272 http://issues.fluidproject.org/browse/FLOE-272
=> FLOE-272: Android and mobile style fixes

demos/index.html, src/css/style.css, src/html/contrast.html, src/html/rangeTemplate.html, src/html/tts.html
http://issues.fluidproject.org/browse/FLOE-275
=> FLOE-275: Set tabindex on controls

demos/index.html, src/css/style.css, src/js/navButtons.js, tests/html/navButtons-Tests.html, tests/js/navButtonsTests.js
@cindyli, could you have a look at this? In addition to CSS changes, there are small markup changes and an associated change to the JS for the labels.
=> FLOE-296: Restyle the next/back buttons

src/css/style.css, src/messages/congratulations.json, src/messages/lang.json, src/messages/speakText.json
@jobara, @cindyli - some small updates to the text in the existing screens.
=> FLOE-302: Update text in FD interface

src/js/keyboardInput.js, tests/all-tests.html, tests/html/keyboardInput-Tests.html, tests/js/keyboardInputTests.js, tests/manualTests/html/keyboardInput-manualTests.html
http://issues.fluidproject.org/browse/FLOE-301
=> FLOE-301: Implement a sticky keys simulator

demos/index.html, src/js/firstDiscoveryEditor.js, src/js/helpButton.js, src/messages/firstDiscovery.json, tests/all-tests.html, tests/html/firstDiscoveryEditor-Tests.html, tests/html/helpButton-Tests.html, tests/js/helpButtonTests.js
http://issues.fluidproject.org/browse/FLOE-300
=> FLOE-300: Add a component to make the "help" button localizable

src/js/navButtons.js, tests/html/navButtons-Tests.html, tests/js/firstDiscoveryEditorTests.js, tests/js/navButtonsTests.js, tests/js/testUtils.js
as requested by Dana in the designs.
=> FLOE-323: Enable back button on final congrats screen

src/js/keyboardInput.js, src/messages/firstDiscovery.json, tests/html/keyboardInput-Tests.html, tests/js/keyboardInputTests.js, tests/manualTests/html/keyboardInput-manualTests.html
http://issues.fluidproject.org/browse/FLOE-307
=> FLOE-307: Add a tooltip to the keyboardInput component

src/messages/textSize.json
http://issues.fluidproject.org/browse/FLOE-332
=> FLOE-332: Until we separate text size and controls size, adjust language in text size panel

src/js/firstDiscoveryEditor.js
http://issues.fluidproject.org/browse/FLOE-297
=> FLOE-297: Binding the selfVoicing to speak model

src/js/firstDiscoveryEditor.js, src/lib/infusion/VERSION.md, src/lib/infusion/infusion-custom.js, tests/js/firstDiscoveryEditorTests.js, tests/js/selfVoicingTests.js
Hooking up the speechRate model value to the selfVoicing. This enables it to be enacted in the first discovery tool.
Also includes an update of Infusion.
http://issues.fluidproject.org/browse/FLOE-318
=> FLOE-318: Connecting speechRate to selfVoicing

demos/index.html, src/css/style.css, src/html/firstDiscovery.html, src/js/panels.js, src/messages/showSounds.json, src/schemas/schemas.js, tests/html/firstDiscoveryEditor-Tests.html, tests/html/panels-Tests.html, tests/js/firstDiscoveryEditorTests.js, tests/js/panelsTests.js, tests/js/testUtils.js
http://issues.fluidproject.org/browse/FLOE-319
=> FLOE-319: Adding the showSound panel

src/js/stickyKeysAdjuster.js
http://issues.fluidproject.org/browse/FLOE-349
=> FLOE-349: only close tooltip if it already exists

src/js/panels.js
http://issues.fluidproject.org/browse/FLOE-351
=> FLOE-351: Corrected stickyKeys preferenceMap

src/js/keyboardInput.js, tests/js/keyboardInputTests.js
http://issues.fluidproject.org/browse/FLOE-340
=> FLOE-340: Unlatch shift on focusout

demos/index.html, src/css/style.css
- fixed clipping of confirm checkmark in Safari
- fixed the white bar that was appearing to right of last icon in icon bar.
=> FLOE-350: Styling fixes

demos/index.html, src/html/contrast.html, src/html/keyboard.html, src/html/lang.html, src/html/rangeTemplate.html, src/html/rangeWithDisabledMsgTemplate.html, src/html/tts.html, src/html/yesNo.html, tests/html/panels-Tests.html
In order to use the default browser tab orders.
=> FLOE-358: Removed "tabindex" attribute

src/html/rangeTemplate.html, src/html/rangeWithDisabledMsgTemplate.html
You can test this on desktop. Just resize your browser window smaller and you should see the difference between this pull and master.
=> FLOE-355: Fixed layout in mobile for range adjuster

src/js/panels.js, src/messages/keyboard_en-US.json, src/messages/keyboard_es-MX.json, src/messages/keyboard_fr-FR.json
http://issues.fluidproject.org/browse/FLOE-363
=> FLOE-363: Voicing sticky keys state

src/css/style.css, src/js/firstDiscoveryEditor.js
Requires: https://github.com/fluid-project/first-discovery/pull/76
http://issues.fluidproject.org/browse/FLOE-327
=> FLOE-327: Adjusted positions of tooltips

src/css/style.css, tests/js/panelsTests.js
https://issues.fluidproject.org/browse/FLOE-333
=> FLOE-333: Separate browsing the language panel from activation

src/css/style.css, src/messages/captions_fr-FR.json, src/messages/congratulations_fr-FR.json, src/messages/contrast_fr-FR.json, src/messages/firstDiscovery_fr-FR.json, src/messages/keyboard_fr-FR.json, src/messages/lang_en-US.json, src/messages/lang_es-MX.json, src/messages/lang_fr-FR.json, src/messages/onScreenKeyboard_fr-FR.json, src/messages/showSounds_fr-FR.json, src/messages/speakText_fr-FR.json, src/messages/speechRate_fr-FR.json, src/messages/textSize_fr-FR.json, src/messages/welcome_fr-FR.json
https://issues.fluidproject.org/browse/FLOE-415
=> FLOE-415: Adding missing French translations

src/js/panels.js
To clarify the use of setTimeout() in the implementation of the language panel.
=> FLOE-407: Update and add details in a comment

src/js/firstDiscoveryEditor.js, src/js/panels.js, src/lib/infusion/VERSION.md, tests/html/panels-Tests.html, tests/js/panelsTests.js, tests/lib/infusion/lib/mockjax/js/jquery.mockjax.js
To send a request to the preferences server to save user selected preferences.
https://issues.fluidproject.org/browse/FLOE-426
=> FLOE-426:  Enhanced the token panel

demos/js/demos.js, demos/prefsServerIntegration/index.html, src/schemas/schemas.js
=> FLOE-428: Move the demo path override into the demo

demos/prefsServerIntegration/index.html, src/js/firstDiscoveryEditor.js, src/js/panels.js, src/schemas/schemas.js, tests/html/firstDiscoveryEditor-Tests.html, tests/js/firstDiscoveryEditorTests.js, tests/js/panelsTests.js, tests/js/testUtils.js
The detail of GPII-1490: http://issues.gpii.net/browse/GPII-1490
The corresponding pull request for updating the API docs: https://github.com/acheetham/docs-first-discovery/pull/2
=> GPII-1490: Add the ontology name when sending save request to the first discovery server
